build:                            false

environment:
    PYTHON:                       "C:\\Python37"

    CONAN_REFERENCE:              "OGRE/1.11.6"
    CONAN_USERNAME:               "anotherfoxguy"
    CONAN_LOGIN_USERNAME:         "anotherfoxguy"
    CONAN_CHANNEL:                "testing"
    CONAN_UPLOAD:                 "https://api.bintray.com/conan/anotherfoxguy/ror-dependencies"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS:  16
          CONAN_BUILD_TYPES:      Release
          CONAN_ARCHS:            x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS:  16
          CONAN_BUILD_TYPES:      Debug
          CONAN_ARCHS:            x86_64

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade -q
  - pip.exe install conan_package_tools -q
  - conan user # It creates the conan data directory

build_script:
- ps: >-
    iex (new-object net.webclient).downloadstring('https://get.scoop.sh')

    scoop bucket add Ash258 https://github.com/Ash258/scoop-Ash258.git
    
    scoop install DirectX-SDK

test_script:
  - python build.py
