build:                            false

environment:
    PYTHON:                       "C:\\Python37"

    CONAN_REFERENCE:              "OGRE/1.11.6-with-patches"
    CONAN_USERNAME:               "anotherfoxguy"
    CONAN_LOGIN_USERNAME:         "anotherfoxguy"
    CONAN_CHANNEL:                "testing"
    CONAN_UPLOAD:                 "https://api.bintray.com/conan/anotherfoxguy/ror-dependencies"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS:  16
          CONAN_BUILD_TYPES:      Release
          CONAN_ARCHS:            x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS:  16
          CONAN_BUILD_TYPES:      Debug
          CONAN_ARCHS:            x86_64

install:
  - choco install wget -y
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade -q
  - pip.exe install conan_package_tools -q
  - conan user # It creates the conan data directory
  - mkdir "C:\apps\Microsoft DirectX SDK" && cd "C:\apps\Microsoft DirectX SDK"
  - wget -nv https://anotherfoxguy.com/Files/Microsoft_DirectX_SDK.7z
  - 7z x Microsoft_DirectX_SDK.7z
  - cd C:\projects\conan-ogre

test_script:
  - setx DXSDK_DIR "C:\apps\Microsoft DirectX SDK"
  - python build.py
